apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "selvo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selvo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "selvo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selvo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "selvo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: selvo-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "selvo.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["selvo-api"]
          ports:
            - name: http
              containerPort: {{ include "selvo.port" . }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "selvo.fullname" . }}
            - secretRef:
                name: {{ include "selvo.fullname" . }}
                optional: true
          {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: selvo-cache
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: selvo-cache
          persistentVolumeClaim:
            claimName: {{ include "selvo.fullname" . }}-cache
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
