apiVersion: v1
kind: Secret
metadata:
  name: {{ include "selvo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selvo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.selvo.stripeWebhookSecret }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.selvo.stripeWebhookSecret | quote }}
  {{- end }}
  {{- if .Values.selvo.stripeSecretKey }}
  STRIPE_SECRET_KEY: {{ .Values.selvo.stripeSecretKey | quote }}
  {{- end }}
  {{- if .Values.selvo.githubToken }}
  GITHUB_TOKEN: {{ .Values.selvo.githubToken | quote }}
  {{- end }}
  {{- if .Values.selvo.nvdApiKey }}
  NVD_API_KEY: {{ .Values.selvo.nvdApiKey | quote }}
  {{- end }}
  {{- if .Values.selvo.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.selvo.openaiApiKey | quote }}
  {{- end }}
